### ISSUE TITLE
CodeCommit - NullReferenceException for previously-working credentials in VS2017

### ISSUE THREAD

**Issue by RickyAppSe** [aws/aws-toolkit-visual-studio#11]
## Expected Behavior

Open Visual Studio 2017. In Team Explorer, have the projects ready to be opened and worked on under AWS CodeCommit.

## Current Behavior

Where "AWS CodeCommit" should be in Team Explorer, the title is instead: "Error".

Where the projects should be is the following exception stack trace:

```
System.TypeInitializationException: The type initializer for 'Amazon.AWSToolkit.VisualStudio.TeamExplorer.CredentialManagement.TeamExplorerConnection' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Amazon.AWSToolkit.VisualStudio.TeamExplorer.CredentialManagement.TeamExplorerConnection..cctor()
   --- End of inner exception stack trace ---
   at Amazon.AWSToolkit.VisualStudio.TeamExplorer.CredentialManagement.TeamExplorerConnection.add_OnTeamExplorerBindingChanged(TeamExplorerBindingChanged value)
   at Amazon.AWSToolkit.VisualStudio.TeamExplorer.CodeCommit.Model.ConnectSectionViewModel..ctor()
   at Amazon.AWSToolkit.VisualStudio.TeamExplorer.CodeCommit.Connect.ConnectionSection.CreateViewModel(SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.TeamExplorerSectionBase.Initialize(Object sender, SectionInitializeEventArgs e)
   at Amazon.AWSToolkit.VisualStudio.TeamExplorer.CodeCommit.Connect.ConnectionSection.Initialize(Object sender, SectionInitializeEventArgs e)
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)
```

## Possible Solution
I have no idea. I haven't changed anything - I was on a recent version of VS 2017, and AWS Toolkit for VS 2017 & 2019 was on the latest version, and previously this setup has been working since I began using it about 5 months ago.

I tried updating VS2017 to the latest version (it was less than a month our of date). No luck, error message still the same.

I also tried completely uninstalling and re-installing the AWS Toolkit for VS2017 extension. No luck, error message still the same. And no, it didn't even ask me to enter any credentials again or anything, it's just immediately presenting me with that error.

EDIT: I also tried restarting my computer. No luck, error message still the same.

## Steps to Reproduce (for bugs)

1. Have working credentials and be connected to projects successfully for 5 months.

2. One day, have AWS CodeCommit crash?

Maybe this was a Windows Update issue?

Please help.

## Context

This is how I connect to my client's codebase. With this out, it will severely hamper my ability to do work as a contractor.

## Your Environment

VS2017 Professional, v15.9.10.

Windows 10 Pro, 64-bit version.

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by awschristou** [comment]
I believe this issue was fixed in 1.15.2.0 (2019-05-23) ([Changelog](https://github.com/aws/aws-toolkit-visual-studio/blob/main/CHANGELOG.md)).

If you are still having problems while using the most recent versions of the Toolkit, please open a new issue.
