### ISSUE TITLE
How do I use the CLI to do a lambda serverless deployment for a dotnet 5 project.

### ISSUE THREAD

**Issue by battarro** [aws/aws-toolkit-visual-studio#144]
### Good morning. 

I'm trying to use the CLI to do an automated deployments to AWS lambda of my C# lambda project.
With dotnet 3.1 I would do the following.

`dotnet lambda deploy-serverless  --configuration debug --stack-name custom-webhook-dev --s3-bucket custom-deployment-dev --template serverless.dev.template --region us-east-1 --s3-prefix custom-salesforce-integration- `

This will take care of my deployment to my dev environment, while my production deployment would be similar but replacing `dev` with `prod` and debug for release.

But with 5.0 I get the following issue :

`Amazon Lambda Tools for .NET Core applications (3.2.3)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet

Processing CloudFormation resource AspNetCoreFunction
Initiate packaging of . for resource AspNetCoreFunction
Unknown error executing command: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Amazon.Lambda.Tools.LambdaUtilities.DetermineTargetFrameworkFromLambdaRuntime(String lambdaRuntime, String projectLocation) in C:\codebuild\tmp\output\src109826539\src\src\Amazon.Lambda.Tools\LambdaUtilities.cs:line 38
   at Amazon.Lambda.Tools.TemplateProcessor.TemplateProcessorManager.PackageDotnetProjectAsync(IUpdateResourceField field, String location) in C:\codebuild\tmp\output\src109826539\src\src\Amazon.Lambda.Tools\TemplateProcessor\TemplateProcessorManager.cs:line 223
   at Amazon.Lambda.Tools.TemplateProcessor.TemplateProcessorManager.ProcessUpdatableResourceAsync(String templateDirectory, IUpdateResourceField field) in C:\codebuild\tmp\output\src109826539\src\src\Amazon.Lambda.Tools\TemplateProcessor\TemplateProcessorManager.cs:line 167
   at Amazon.Lambda.Tools.TemplateProcessor.TemplateProcessorManager.TransformTemplateAsync(String templateDirectory, String templateBody) in C:\codebuild\tmp\output\src109826539\src\src\Amazon.Lambda.Tools\TemplateProcessor\TemplateProcessorManager.cs:line 95
   at Amazon.Lambda.Tools.Commands.DeployServerlessCommand.PerformActionAsync() in C:\codebuild\tmp\output\src109826539\src\src\Amazon.Lambda.Tools\Commands\DeployServerlessCommand.cs:line 167
   at Amazon.Common.DotNetCli.Tools.Commands.BaseCommand`1.ExecuteAsync() in C:\codebuild\tmp\output\src109826539\src\src\Amazon.Common.DotNetCli.Tools\Commands\BaseCommand.cs:line 44
   `

It seems to be missing the key for `DetermineTargetFrameworkFromLambdaRuntime `

What value should this be? What I'm trying to do is just automate the deployment to lambda of my project, Ideally i would like one file to deploy to dev, and 1 file to deploy to production.

Thank you in advance.

**Comment by battarro** [comment]
This is the serverless.dev.template file.
![image](https://user-images.githubusercontent.com/10959815/106615655-a8d56d00-653a-11eb-93ac-54bc7a5105f1.png)

One thing that it is missing is the "Runtime" setting that was in 3.1.
Am I supposed to add this on this file or or the command line? And if yes, what value should it be?

**Comment by battarro** [comment]
I added this same question on the aws-extensions-for-dotnet-cli repository so feel free to delete this if it is not relevant here.

**Comment by awschristou** [comment]
Associated issue: https://github.com/aws/aws-extensions-for-dotnet-cli/issues/158
