### ISSUE TITLE
Object reference not set error whle deploying .NET 5 elastic beanstalk app

### ISSUE THREAD

**Issue by bzuillsmith** [aws/aws-toolkit-visual-studio#159]
When publishing, we get an error. The logs show the following

    Configuring application bundle for a Linux deployment
    Writing Procfile for deployment bundle
    Unknown error executing command: Object reference not set to an instance of an object.
       at Amazon.ElasticBeanstalk.Tools.EBUtilities.SetupPackageForLinux(IToolLogger logger, EBBaseCommand command, DeployEnvironmentProperties options, String publishLocation, String reverseProxy, Nullable`1 applicationPort)
       at Amazon.ElasticBeanstalk.Tools.Commands.DeployEnvironmentCommand.<PerformActionAsync>d__16.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Amazon.Common.DotNetCli.Tools.Commands.BaseCommand`1.<ExecuteAsync>d__10.MoveNext()

We have no hint as to why this is happening. It has worked for us in the past. The last time we ran a publish was a month ago or so.

**Comment by awschristou** [comment]
Hi @bzuillsmith , does it help if you clean your solution and rebuild it before deploying?

Failing that, in your project's `bin\xxx\net5.0\publish` folder (where xxx is Debug or Release), can you please check if there is a *.runtimeconfig.json file present?

**Comment by bzuillsmith** [comment]
Sorry, we just recently figured it out. The project had some project properties set that conflicted with the deployment. I don't recall all the names and of the properties, but it was set to target win10-x64 and self-contained was set to true, things like that. These all likely conflict with what eb deploy on a linux platform requires. It would be nice if AWS toolkit could somehow detect these conflicting properties and give a helpful message, but ultimately the issue was we should not have set those in the project file. Feel free to close this, or let me know if you want me to paste the part of our project causing the problems for you to reproduce.
