### ISSUE TITLE
502.5 Error on successful ELB publish

### ISSUE THREAD

**Issue by jayadvocatia** [aws/aws-toolkit-visual-studio#209]
**Describe the bug**

Using Visual Studio 2022 and the AWS tool kit, a publish of a web application shows successful, but returns a 502.5.

A colleague can publish the same application to the same environment from Visual Studio 2019 and it works.  I was too before upgrading to 2022.

**Comment by awschristou** [comment]
Are you both deploying to the same account or to separate accounts. If you are deploying to separate accounts, your respective deployments may be using different service roles, depending on whether or not you've deployed in the past (specifically, prior to versions 1.20.2.0 and 1.18.0.0, see [Changelog](https://github.com/aws/aws-toolkit-visual-studio/blob/main/CHANGELOG.md))

**Comment by jayadvocatia** [comment]
I should have mentioned that 2019 publish behaves the same way after the 
2022 upgrade..  is there some common AWS toolkit file or something that 
is common to both?

**Comment by jayadvocatia** [comment]
Hi Christopher, This is the log from the ELB instance:  Mentions a 
DLLNotFoundException.. the zip looks like it has everything at a quick 
glance.. like I said, this same application is able to be published no 
problem for a Team Foundation user that hasn't upgraded to 2022 yet.  
And the Web Application runs locally from 2022 without issue.. but when 
publishing with the AWS Toolkit, it results in the 502.5 and log 
below... any ideas?  Thanks, Jay


EventLog Application:


2022-01-08T15:55:52.000Z Error 0:(0) IIS AspNetCore Module - Application 'MACHINE/WEBROOT/APPHOST/DEFAULT WEB SITE' with physical root 'C:\inetpub\AspNetCoreWebApps\app\' failed to start process with commandline 'C:\inetpub\AspNetCoreWebApps\app\Web.BenefitScreenings.exe ', ErrorCode = '0x80004005' : ff.
2022-01-08T15:55:52.000Z Information 0:(0) Windows Error Reporting - Fault bucket , type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Web.BenefitScreenings.exe
P2: 1.1.6.6
P3: b6834273
P4: Microsoft.AspNetCore.Server.Kestrel
P5: 1.1.3.30908
P6: 59b3048e
P7: e6
P8: 0
P9: System.AggregateException
P10:

Attached files:

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Web.BenefitScree_c8fd8fd11ad56b3ef75e9e7446ffecb8752fc037_fdd1c7c2_02533deb

Analysis symbol:
Rechecking for solution: 0
Report Id: 73d37a19-709b-11ec-829b-060e596b22de
Report Status: 4100
Hashed bucket:
2022-01-08T15:55:51.000Z Error 100:Application Crashing Events Application Error - Faulting application name: Web.BenefitScreenings.exe, version: 1.1.6.6, time stamp: 0xb6834273
Faulting module name: KERNELBASE.dll, version: 6.3.9600.19425, time stamp: 0x5d26b6e9
Exception code: 0xe0434352
Fault offset: 0x000000000000908c
Faulting process id: 0x794
Faulting application start time: 0x01d804a8351723b1
Faulting application path: C:\inetpub\AspNetCoreWebApps\app\Web.BenefitScreenings.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 73d37a19-709b-11ec-829b-060e596b22de
Faulting package full name:
Faulting package-relative application ID:
2022-01-08T15:55:51.000Z Error 0:(0) .NET Runtime - Application: Web.BenefitScreenings.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException
    at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv+NativeMethods.uv_loop_size()
    at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvLoopHandle.Init(Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv)
    at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelThread.ThreadStart(System.Object)

Exception Info: System.AggregateException
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean)
    at System.Threading.Tasks.Task.Wait(Int32, System.Threading.CancellationToken)
    at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.Start(Int32)
    at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[[Microsoft.AspNetCore.Hosting.Internal.HostingApplication+Context, Microsoft.AspNetCore.Hosting, Version=1.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](Microsoft.AspNetCore.Hosting.Server.IHttpApplication`1<Context>)
    at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
    at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(Microsoft.AspNetCore.Hosting.IWebHost, System.Threading.CancellationToken, System.String)
    at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(Microsoft.AspNetCore.Hosting.IWebHost)
    at Web.BenefitScreenings.Program.Main(System.String[])

**Comment by awschristou** [comment]
One of the differences introduced in version 1.23.2.0 is that when you publish to windows compute, the runtime `win-x64` is used in the compile/publish calls. Previously there was no runtime specified - it used to only provide a runtime (`linux-x64`) when publishing to linux compute. Is there a chance your csproj has some filters that are runtime dependent? 

Possible references:
- https://stackoverflow.com/questions/39781687/system-dllnotfoundexception-unable-to-load-dll-libuv-when-publishing-net-cor
- https://github.com/aspnet/KestrelHttpServer/issues/1625

**Comment by jayadvocatia** [comment]
* Tried replacing with win7-x64..
  * tried removing <RuntimeIdentifier> altogether...

and neither made any impact... here's the Property Group from the csproj 
file.

   <PropertyGroup>
     <TargetFramework>net472</TargetFramework>
     <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
   </PropertyGroup>

**Comment by jayadvocatia** [comment]
We did a comparison on the AWS publish zip created by the 2 
environments..  the VS 2022 version is missing the Libuv.dll - which is 
what the AWS logs point to as the problem.  Any thoughts?
