### ISSUE TITLE
Have Publish to AWS Lambda use the profile in asw-lambda-tools-default

### ISSUE THREAD

**Issue by genifycom** [aws/aws-toolkit-visual-studio#23]
**Is your feature request related to a problem? Please describe.**
In Visual Studio 15.9.14 the Publish to AWS Lambda defaults to the last used profile.

**Describe the solution you'd like**
I work with many clients and multiple AWS profiles. I cannot tell you the number of times a "Publish to AWS Lambda" has published to the wrong client.
The aws-lambda-tools-default.json contains the profile to use. Please default this to the profile when "Publish to AWS Lambda" is used.

Try opening Visual Studio on two projects (different client projects with different profiles). Switching between the two does not switch AWS profiles.

**Describe alternatives you've considered**
No easy workaround

**Additional context**
This is vital if you are working with multiple projects, multiple clients and multiple AWS profiles.

**Comment by jerhewet** [comment]
This might also be an issue with Visual Studio Code, but it is also very much an issue with the Visual Studio IDE.  I'm using Visual Studio Professional 2019, and the steps to reproduce outlined by @genifycom will always replicate the issue, because selecting "Publish to AWS Lambda..." does not use the profile value from the current copy of "aws-lambda-tools-defaults.json".

I have two separate MSBuild targets set up in my project file that will replace the existing "aws-lambda-tools-defaults.json" file depending on the build configuration (Debug or Release).  The JSON file is always being replaced when I change the build target (read as: the lambda setting for "profile" is completely different between Debug and Release), but when I select "Publish to AWS Lambda" after doing a clean and rebuild the "Upload to AWS Lambda" dialog is still using the last selected profile instead of the new profile contained in the "aws-lambda-tools-defaults.json" file.

The solution to this bug is to *always* reload the settings from the "aws-lambda-tools-defaults.json" file *before* displaying the "Upload to AWS Lambda" dialog, and not use any cached settings for the publish.

**Comment by jerhewet** [comment]
Not sure if this is relevant, but it seems the "Publish to AWS Lambda" dialog is looking for a "project.json" file and not finding one.  Can I create this JSON file myself and place it in the project directory?

2020-01-24 06:33:23,609 [1] ERROR Amazon.AWSToolkit.Lambda.WizardPages.PageUI.UploadFunctionDetailsPage - Error searching for default assembly in D:\Documents\Visual Studio\Projects\[project name redacted]
System.IO.FileNotFoundException: Could not find file 'D:\Documents\Visual Studio\Projects\[project name redacted]\project.json'.
File name: 'D:\Documents\Visual Studio\Projects\[project name redacted]\project.json'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at Amazon.AWSToolkit.Lambda.WizardPages.PageUI.UploadFunctionDetailsPage.InitializeControlForNETCore(String sourcePath)

**Comment by klaytaybai** [comment]
Also reported in https://github.com/aws/aws-sdk-net/issues/1521

**Comment by ashishdhingra** [comment]
@awschristou Just wanted to check if there is any movement on this issue.

Thanks,
Ashish

**Comment by awschristou** [comment]
Hi @ashishdhingra , there hasn't been any movement on this issue.

**Comment by awschristou** [comment]
Closing as duplicate of #224
