### ISSUE TITLE
AWS Toolkit for Visual Studio 2019

### ISSUE THREAD

**Issue by joshiamit24** [aws/aws-toolkit-visual-studio#241]
**Computer (please complete the following information):**

- Windows Version:  10 Enterprise
- Visual Studio Version: 2019  Enterprise
- AWS Toolkit for Visual Studio Version:

**Install log**
4/21/2022 4:50:26 PM - 		Microsoft.VisualStudio.Community
4/21/2022 4:50:26 PM - 			Version : [16.0,17.0)
4/21/2022 4:50:26 PM - 			ProductArchitecture : x86
4/21/2022 4:50:26 PM - 
4/21/2022 4:50:26 PM - 	References         : 
4/21/2022 4:50:26 PM - 	Prerequisites      : 
4/21/2022 4:50:26 PM - 		-------------------------------------------------------
4/21/2022 4:50:26 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
4/21/2022 4:50:26 PM - 		Name         : Visual Studio core editor
4/21/2022 4:50:26 PM - 		Version      : [16.0,17.0)
4/21/2022 4:50:26 PM - 
4/21/2022 4:50:26 PM - Signature Details...
4/21/2022 4:50:26 PM - 	Extension is signed with a valid signature.
4/21/2022 4:50:26 PM - 
4/21/2022 4:50:26 PM - System.InvalidOperationException: VSHiveStub.exe failed: Unknown error
   at VSIXInstaller.LocationBasedSKU.SettingsManagerData.get_RegRootHiveOverride()
   at VSIXInstaller.LocationBasedSKU.get_RegRootHiveOverride()
   at VSIXInstaller.SupportedVSSKU.InitializeSettingsManager()
   at VSIXInstaller.SupportedVSSKU.get_Host()
   at VSIXInstaller.SupportedVSSKU.CreateExtensionEngine()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at VSIXInstaller.ExtensionService.GetExtensionEngineForApplicableSKU(ICommandLineData cmdLineData, SupportedVSSKU supportedSKU, IInstallableExtension installableExtension, List`1 applicableSKUs, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.ComputeInstallableExtensions(IStateData stateData, Boolean isRepairSupported, Boolean isExtensionPack, IDictionary`2 skuDataMapping, IList`1 installableExtensionsPaths)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Any other information**
I am on company VPN while installing toolkit but I tried without VPN as well. Also the same issue coming for VS 2022 toolkit installation.

**Comment by awschristou** [comment]
Hi @joshiamit24 thank you for reaching out. Are you having similar issues installing other Visual Studio extensions?

Your installation of Visual Studio might be in a bad state. Have you tried launching the "Visual Studio Installer" from the start menu, and running Repair against your installation?

![image](https://user-images.githubusercontent.com/39839589/164554850-b7739f45-2c99-4f03-9390-71fd5d5fbbca.png)

**Comment by joshiamit24** [comment]
Ok let me try this.

**Comment by joshiamit24** [comment]
same issue again. 

![v](https://user-images.githubusercontent.com/8158164/164563152-6efb6455-9e6b-4a37-b4c5-8f4832d0be4b.jpg)

**Comment by awschristou** [comment]
Out of curiosity, does the same thing happen when you install other Visual Studio extensions?

Extensions are installed through the Visual Studio VSIX installer, you might need to reach out to the Visual Studio team for assistance - see https://developercommunity.visualstudio.com/report for details.

**Comment by joshiamit24** [comment]
It seems this issue is appearing on office laptop. I tried on personal laptop and I can install AWS toolkit without any issues.
Not sure what is the issue with office laptop.

**Comment by awschristou** [comment]
The Toolkit does require (Windows) Administrator permissions in order to install it. I am not sure if the error you are seeing would be the result of not having those permissions though.

**Comment by joshiamit24** [comment]
I am admin on office laptop. As per log it fails on VSHiveStub.exe failed: Unknown error

**Comment by SamipJ** [comment]
I am facing same issue. Did anybody get a solution?
