### ISSUE TITLE
Error Trying to Install AWS Toolkit on Visual Studio 2022 on Windows 11

### ISSUE THREAD

**Issue by gfullerhexa** [aws/aws-toolkit-visual-studio#242]
**Describe the bug**
When I try to install the AWS Toolkit for VS2022, it fails the installation and does not install the product.  I am using the VS2022 link from this page: https://aws.amazon.com/visualstudio/

**Expected behavior**
I expect that the application installs onto VS 2022 and that when I load VS 2022 I can see the AWS Toolkit extension running with its toolbars and configuration windows.

**Screenshots**

**Computer (please complete the following information):**

- Windows Version: Window 11 Pro (Version: 21H2, OS Build: 22000.613)
- Visual Studio Version: Visual Studio 2022 (17.1.5)
- AWS Toolkit for Visual Studio Version:  v17

**Additional context**
Here is the installation log:
[dd_VSIXInstaller_20220424114532_9798.log](https://github.com/aws/aws-toolkit-visual-studio/files/8550114/dd_VSIXInstaller_20220424114532_9798.log)

Here is the section in the log where I see the errors start:

4/24/2022 11:45:40 AM - Skipping 'C:\Users\Gabriel\AppData\Local\Microsoft SDKs' as it doesn't exist
4/24/2022 11:45:40 AM - Beginning to install extension to Visual Studio Community 2022...
4/24/2022 11:45:40 AM - Failed to get profile list from registry.
4/24/2022 11:45:40 AM - VSIX TaskScheduler: VSIX Update Configuration task has not been successfully registered.
4/24/2022 11:45:40 AM - No mapping between account names and security IDs was done
4/24/2022 11:45:43 AM - Skipping non-applicable package Microsoft.VisualStudio.Debugger.DbgHelp.Win8: The current OS Version '10.0.22000.0' is not in the supported version range '[6.1,6.3]'.
4/24/2022 11:45:43 AM - Skipping non-applicable package Microsoft.VisualStudio.Debugger.Remote.DbgHelp.Win8: The current OS Version '10.0.22000.0' is not in the supported version range '[6.1,6.3]'.
4/24/2022 11:45:43 AM - Skipping non-applicable package Microsoft.VisualStudio.Debugger.Remote.DbgHelp.Win8: The current OS Version '10.0.22000.0' is not in the supported version range '[6.1,6.3]'.
4/24/2022 11:45:43 AM - Skipping non-applicable package Microsoft.Windows.UniversalCRT.Msu.8: The current OS Version '10.0.22000.0' is not in the supported version range '[6.2,6.3)'.
4/24/2022 11:45:43 AM - Skipping non-applicable package Microsoft.Windows.UniversalCRT.Msu.81: The current OS Version '10.0.22000.0' is not in the supported version range '[6.3,6.4)'.
4/24/2022 11:45:43 AM - Skipping non-applicable package Microsoft.Net.4.8.FullRedist: The current OS Version '10.0.22000.0' is not in the supported version range '[6.1.1,10.0.17763]'.
4/24/2022 11:45:43 AM - Skipping non-applicable package Microsoft.Net.4.8.KB5003306: The current OS Version '10.0.22000.0' is not in the supported version range '[10.0.18362,10.0.18363]'.
4/24/2022 11:45:43 AM - Skipping non-applicable package Microsoft.Net.4.8.KB5003304: The current OS Version '10.0.22000.0' is not in the supported version range '[10.0.19041,10.0.19044]'.
4/24/2022 11:45:43 AM - Skipping non-applicable package Microsoft.Net.4.8.KB5003793: The current OS Version '10.0.22000.0' is not in the supported version range '[10.0.20279,10.0.20348]'.
4/24/2022 11:45:43 AM - Skipping non-applicable package Microsoft.DiagnosticsHub.KB2882822.Win7: The current OS Version '10.0.22000.0' is not in the supported version range '[6.1,6.2)'.
4/24/2022 11:45:43 AM - Skipping non-applicable package Microsoft.Windows.UniversalCRT.Msu.7: The current OS Version '10.0.22000.0' is not in the supported version range '[6.1,6.2)'.
4/24/2022 11:45:43 AM - Skipping non-applicable package Microsoft.VisualStudio.NuGet.PowershellBindingRedirect: The current OS Version '10.0.22000.0' is not in the supported version range '[6.1,6.2)'.
4/24/2022 11:45:43 AM - Windows Installer found the package 'Microsoft.NetCore.AppHostPack.6.0.6.0.4.arm,version=17.1.32406.283,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
4/24/2022 11:45:43 AM - Windows Installer found the package 'Microsoft.NetCore.AppHostPack.6.0.6.0.4.arm64,version=17.1.32406.283,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
4/24/2022 11:45:43 AM - Windows Installer found the package 'Microsoft.NetCore.AppHostPack.6.0.6.0.4.x64,version=17.1.32406.283,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
4/24/2022 11:45:43 AM - Windows Installer found the package 'Microsoft.NetCore.AppHostPack.6.0.6.0.4.x86,version=17.1.32406.283,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
4/24/2022 11:45:43 AM - Windows Installer found the package 'Microsoft.NetCore.SharedFramework.6.0.6.0.4.x64,version=17.1.32406.283,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
4/24/2022 11:45:43 AM - Windows Installer found the package 'Microsoft.NetCore.SharedFramework.6.0.6.0.4.x86,version=17.1.32406.283' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
4/24/2022 11:45:43 AM - Windows Installer found the package 'Microsoft.NetCore.TargetingPack.6.0.6.0.4,version=17.1.32406.283,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
4/24/2022 11:45:43 AM - Windows Installer found the package 'Microsoft.NetCore.Templates.6.0.6.0.202-servicing.22172.7,version=17.1.32406.283,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
4/24/2022 11:45:43 AM - Windows Installer found the package 'Microsoft.WindowsDesktop.SharedFramework.6.0.6.0.4.x64,version=17.1.32406.283,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
4/24/2022 11:45:43 AM - Windows Installer found the package 'Microsoft.WindowsDesktop.SharedFramework.6.0.6.0.4.x86,version=17.1.32406.283' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
4/24/2022 11:45:43 AM - Windows Installer found the package 'Microsoft.WindowsDesktop.TargetingPack.6.0.6.0.4,version=17.1.32406.283,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
4/24/2022 11:45:43 AM - Windows Installer found the package 'Microsoft.NetCore.HostFXR.6.0.4.x64,version=17.1.32406.283,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
4/24/2022 11:45:43 AM - Windows Installer found the package 'Microsoft.NetCore.HostFXR.6.0.4.x86,version=17.1.32406.283' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
4/24/2022 11:45:43 AM - Windows Installer found the package 'Microsoft.NetCore.SharedHost.6.0.0,version=17.1.32406.283,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
4/24/2022 11:45:43 AM - Windows Installer found the package 'Microsoft.NetCore.Toolset.6.0.202,version=17.1.32406.283,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
4/24/2022 11:45:43 AM - Skipping non-applicable package Microsoft.Azure.PowerShell: Required conditions are not satisfied: Not Powershell5
4/24/2022 11:45:43 AM - Skipping non-applicable package Microsoft.VisualStudio.OfficeDeveloperTools.WindowsIdentityFoundation.Msu: The current OS Version '10.0.22000.0' is not in the supported version range '(,6.2)'.
4/24/2022 11:45:46 AM - Package '0B82CB16-0E52-4363-9BC0-61E758689176,version=1.28.0.0' failed to install. System.IO.IOException: The file 'C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Amazon Web Services LLC\AWSToolkit.VS2010\Amazon.AwsToolkit.Telemetry.Events.dll' already exists.
   at Microsoft.VisualStudio.Setup.Installer.VsixInstaller.<InstallCoreInternal>g__install|31_1(PackagePart part, Boolean saveExtensionManifest, <>c__DisplayClass31_0& , <>c__DisplayClass31_1& , <>c__DisplayClass31_2& , <>c__DisplayClass31_3& , <>c__DisplayClass31_4& )
   at Microsoft.VisualStudio.Setup.Installer.VsixInstaller.InstallCoreInternal(String localPath, String installDir, InstallablePackage pkg)
   at Microsoft.VisualStudio.Setup.Installer.FileInstaller.<>c__DisplayClass7_0.<InstallCore>b__0()
   at Microsoft.VisualStudio.Setup.Installer.FileInstaller.DoAction(Func`1 action)
   at Microsoft.VisualStudio.Setup.Installer.FileInstaller.InstallCore(String localPath, String installDir, InstallablePackage pkg)
   at Microsoft.VisualStudio.Setup.Installer.InstallerBase.InstallHelper(InstallData installData)
4/24/2022 11:45:46 AM - Skipping cache of package 'Component.0B82CB16-0E52-4363-9BC0-61E758689176,version=1.28.0.0' since the package or a parent package had a vital failure.
4/24/2022 11:46:05 AM - Install Error : System.AggregateException: One or more errors occurred. ---> Microsoft.VisualStudio.Setup.PackageFailureException: Package '0B82CB16-0E52-4363-9BC0-61E758689176' failed to install
   at Microsoft.VisualStudio.Setup.InstallOperation.Run(CancellationToken token)
   at Microsoft.VisualStudio.Setup.Engine.RunOperation(InstallOperation installOperation, CancellationToken token, ExecuteAction action, ITelemetryOperation telemetryOperation)
   at Microsoft.VisualStudio.Setup.Engine.RunCoreOperation(InstallOperation coreOperation, ExecuteAction action, ITelemetryOperation telemetryOperation, CancellationToken token)
   at Microsoft.VisualStudio.Setup.Engine.Install(Product product, String destination, CancellationToken token)
   at Microsoft.VisualStudio.ExtensionManager.SetupEngineService.<Install>b__14_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ExtensionManager.SetupEngineService.Install()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
---> (Inner Exception #0) Microsoft.VisualStudio.Setup.PackageFailureException: Package '0B82CB16-0E52-4363-9BC0-61E758689176' failed to install
   at Microsoft.VisualStudio.Setup.InstallOperation.Run(CancellationToken token)
   at Microsoft.VisualStudio.Setup.Engine.RunOperation(InstallOperation installOperation, CancellationToken token, ExecuteAction action, ITelemetryOperation telemetryOperation)
   at Microsoft.VisualStudio.Setup.Engine.RunCoreOperation(InstallOperation coreOperation, ExecuteAction action, ITelemetryOperation telemetryOperation, CancellationToken token)
   at Microsoft.VisualStudio.Setup.Engine.Install(Product product, String destination, CancellationToken token)
   at Microsoft.VisualStudio.ExtensionManager.SetupEngineService.<Install>b__14_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by gfullerhexa** [comment]
This toolkit was not installed and has not ever been installed on this machine. I just built this machine a few months ago and have not been able to install this toolkit since. Any other ideas?

**Comment by gfullerhexa** [comment]
I removed all of the files in the 'C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Amazon Web Services LLC\' folder, restarted and tried again, and now it works.
