### ISSUE TITLE
Publish to AWS not working because my User path has space inside

### ISSUE THREAD

**Issue by maddionatoplus** [aws/aws-toolkit-visual-studio#255]
**Describe the bug**
Publish to AWS from Visual Studio not working because my User path has space inside: "C:Users/Marco Ma/"

This is the error

Generating AWS Cloud Development Kit (AWS CDK) deployment project
Using bootstrapping template from C:\\Users\\Marco Ma\\.aws-dotnet-deploy\\CDKBootstrapTemplate.yaml
Unhandled exception. Amazon.JSII.Runtime.JsiiException: Child process exited unexpectedly!
   at Amazon.JSII.Runtime.Services.Runtime.ReadResponse()
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.Hello()
   at Amazon.JSII.Runtime.Services.ServiceContainer.BuildServiceProvider(ILoggerFactory loggerFactoryOverride)
   at Amazon.JSII.Runtime.Services.ServiceContainer.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Amazon.JSII.Runtime.Services.ServiceContainer.get_ServiceProvider()
   at Amazon.JSII.Runtime.Deputy.JsiiTypeAttributeBase.Load(Assembly assembly)
   at Amazon.JSII.Runtime.Deputy.JsiiTypeAttributeBase.Load(Assembly assembly)
   at Amazon.JSII.Runtime.Deputy.DeputyBase..ctor(DeputyProps props)
   at Constructs.Construct..ctor(DeputyProps props)
   at Amazon.CDK.Stage..ctor(DeputyProps props)
   at Amazon.CDK.App..ctor(IAppProps props)
   at CronoDemo.Program.Main(String[] args) in C:\Users\Marco Ma\.aws-dotnet-deploy\Projects\0weos3hc\Program.cs:line 17
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\Marco'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Subprocess exited with error 3762504530

CronoDev could not be published as ASP.NET Core App to Amazon ECS using Fargate: The AWS CDK Bootstrap, which is the process of provisioning initial resources for the deployment environment, has failed. Please review the output above for additional details [and check out our troubleshooting guide for the most common failure reasons]. You can learn more about CDK bootstrapping at https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html.
CronoDemo failed to publish to AWS.

**Computer (please complete the following information):**

- Windows Version: 10
- Visual Studio Version: 2022
- AWS Toolkit for Visual Studio Version: CDK Version: 2.25.0 (build ae1cb4b)

How can I tell cdk to use a different folder or to escape string path?

**Comment by awschristou** [comment]
Thanks for reporting this issue @maddionatoplus - I have filed a bug (https://github.com/aws/aws-dotnet-deploy/issues/579) with the underlying deployment tool that is used by the Toolkit. Can you please share what version of the AWS Toolkit you are running?  From Visual Studio, open the "Extensions" menu, select "Manage Extensions", select "Installed" on the left sidebar, and select the AWS Toolkit extension. The version will be displayed in the right sidebar.

**Comment by 96malhar** [comment]
@maddionatoplus We have updated our docs with a workaround for this issue. Kindly refer to https://aws.github.io/aws-dotnet-deploy/docs/getting-started/custom-workspace/

Note: When setting up the `AWS_DOTNET_DEPLOYTOOL_WORKSPACE` environment variable, please ensure that it persists across shell sessions.

**Comment by maddionatoplus** [comment]
Hi @96malhar, thank you for your answer.
I have still the same problem, now I am on version 1.32.0.0.
Although I set up the env variable it still looks for "C:\Users\Marco" that is different from the path that I have put in the AWS_DOTNET_DEPLOYTOOL_WORKSPACE variable ("C:\aws-deploy"). 
I verified that it's still the same variable if I open and close the cmd

**Comment by 96malhar** [comment]
Hi @maddionatoplus, the AWS Toolkit for visual studio internally uses a [CLI version of AWS.Deploy.Tools](https://github.com/aws/aws-dotnet-deploy). We have rolled out the above mentioned fix as part of the [version 0.48.15](https://github.com/aws/aws-dotnet-deploy/releases/tag/0.48.15) of the CLI tool. The toolkit is has not yet integrated the latest CLI version and is still using [version 0.47.26](https://github.com/aws/aws-dotnet-deploy/releases/tag/0.47.26)

We will keep you posted once the toolkit integrates the latest CLI version. Meanwhile, can you try and use the CLI tooling to serve your use case?

Documentation for the CLI version - https://aws.github.io/aws-dotnet-deploy/

**Comment by maddionatoplus** [comment]
I can't find from my AWS dashboard the resources that has been created (Cluster and services).

**Comment by awschristou** [comment]
Version 1.34.0.0 of the Toolkit is now available, which uses a newer version of the deploy tooling. 

If your user profile location contains a space, see https://aws.github.io/aws-dotnet-deploy/docs/getting-started/custom-workspace/ for guidance around setting up to work with the Publish to AWS feature.
