### ISSUE TITLE
Publish to AWS App Runner fails without an actionable error

### ISSUE THREAD

**Issue by TommyN** [aws/aws-toolkit-visual-studio#266]
**Describe the bug**

Right clicked the project in Visual Studio 
Selected Publish to AWS (Preview)
Selected ASP.NET Core App to AWS App Runner

```
Publish to AWS failed: Value cannot be null.
Parameter name: source
```

I have 2 development machines. On the first machine wanted to try the new deployment experience and when trying to publish our asp-net core solution I got a nice "Missing system requirements" dialog about missing required Docker installation. Since I don't have enough space to install WSL2 and Docker on this machine I tried my other dev machine.

On the other dev machine I'm running the latest AWS Toolkit 1.32.0.0
When trying to deploy on this machine I didn't get the "Missing system requirements" dialog even though I don't have Docker installed and WSL didn't have any distributions.
I installed Docker for Windows and latest Ubuntu and retried the operation and got:

```
Publish targets found for WebAdmin: 3
Publish to AWS failed: Value cannot be null.
Parameter name: source
```

How can I debug what's going wrong?

**Computer (please complete the following information):**

- Windows Version: Windows 11
- Visual Studio Version: 17.2.4
- AWS Toolkit for Visual Studio Version: 1.32.0.0

**Comment by ashovlin** [comment]
Hello, could you share any error stack traces from `%localappdata%\AWSToolkit\logs\visualstudio\log.txt` from a timestamp near to when the failure occurred? Thanks.

**Comment by prinsloopieter** [comment]
@ashovlin I have the same issue, here is a log snip. Just a note I can get the publish details config settings edit button to reset my deployment configs, that only is available if i change the region 


2022-07-19 06:28:12,917 [1] DEBUG Amazon.AWSToolkit.Publish.Install.VerifyDeployCli - 
Verifying AWS.Deploy.Tools.0.50.2

Signature type: Repository
  Subject Name: CN=NuGet.org Repository by Microsoft, O=NuGet.org Repository by Microsoft, L=Redmond, S=Washington, C=US
  SHA256 hash: 5A2901D6ADA3D18260B9C6DFE2133C95D74B9EEF6AE0E5DC334C8454D1477DF4
  Valid from: 2021/02/16 02:00:00 to 2024/05/16 01:59:59

2022-07-19 06:28:12,923 [1] DEBUG Amazon.AWSToolkit.Publish.Install.DeployCli - Finished initializing aws.deploy.tools
2022-07-19 06:29:58,589 [1] ERROR Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterUtilities - Error configuring Lambda Tester on project. FileName: , FullName: , UniqueName: <MiscFiles>
System.Exception: Unable to determine project FileName
   at Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterUtilities.<EnsureLambdaTesterConfiguredAsync>d__2.MoveNext()
2022-07-19 06:30:39,530 [77] DEBUG Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Starting a deployment session
2022-07-19 06:30:43,942 [1] DEBUG Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Deployment session started
2022-07-19 06:30:44,270 [121] DEBUG Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Republish targets found for IBaaS.IMS.ServiceManagement: 0
2022-07-19 06:30:44,291 [43] DEBUG Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Publish targets found for IBaaS.IMS.ServiceManagement: 5
2022-07-19 06:30:45,475 [113] ERROR Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Error setting deployment target
HTTP Response: 

{"ErrorCode":"UnexpectedError","Message":"Source sequence doesn\u0027t contain any elements.","ProcessExitCode":null}

AWS.Deploy.ServerMode.Client.ApiException: The HTTP status code of the response was not expected (500).

Status: 500
Response: 
{"ErrorCode":"UnexpectedError","Message":"Source sequence doesn\u0027t contain any elements.","ProcessExitCode":null}
   at AWS.Deploy.ServerMode.Client.RestAPIClient.<SetDeploymentTargetAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<InvokeSetDeploymentTargetAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<SetDeploymentTargetAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<SetDeploymentTargetAsync>d__188.MoveNext()
2022-07-19 06:30:45,479 [113] ERROR Amazon.AWSToolkit.Publish.Views.PublishToAwsDocumentControl - Error reloading configuration details
HTTP Response: 

{"ErrorCode":"UnexpectedError","Message":"Source sequence doesn\u0027t contain any elements.","ProcessExitCode":null}

AWS.Deploy.ServerMode.Client.ApiException: The HTTP status code of the response was not expected (500).

**Comment by TommyN** [comment]
@ashovlin 

Here is an extract from the log that I hope is from around the time I tried to deploy:
```
Verifying AWS.Deploy.Tools.0.47.26

Signature type: Repository
  Subject Name: CN=NuGet.org Repository by Microsoft, O=NuGet.org Repository by Microsoft, L=Redmond, S=Washington, C=US
  SHA256 hash: 5A2901D6ADA3D18260B9C6DFE2133C95D74B9EEF6AE0E5DC334C8454D1477DF4
  Valid from: 16.02.2021 01:00:00 to 16.05.2024 01:59:59

2022-06-22 13:19:42,519 [1] DEBUG Amazon.AWSToolkit.Publish.Install.DeployCli - Finished initializing aws.deploy.tools
2022-06-22 13:19:57,342 [11] DEBUG Amazon.AWSToolkit.Telemetry.Internal.TelemetryPublisher - Publishing 8 event(s)
2022-06-22 13:22:21,264 [1] DEBUG Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterEventListener - Registering Debugger events
2022-06-22 13:22:21,279 [1] DEBUG Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterUtilities - Configuring Solution with Lambda Tester
2022-06-22 13:22:30,302 [33] DEBUG Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Attempting to install or update Lambda Tester dotnet tool
2022-06-22 13:22:34,767 [19] INFO  Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - dotnet tool update -g Amazon.Lambda.TestTool-6.0
2022-06-22 13:22:34,767 [19] INFO  Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Tool 'amazon.lambda.testtool-6.0' was reinstalled with the latest stable version (version '0.12.2').

2022-06-22 13:22:34,823 [34] DEBUG Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Lambda Tester already installed: Amazon.Lambda.TestTool-6.0, Project: C:\development\GitHub\FotMob-Poller\AWS\AutoS3VideoTranscoding\AutoS3VideoTranscoding.csproj
2022-06-22 13:22:34,832 [28] DEBUG Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Attempting to install or update Lambda Tester dotnet tool
2022-06-22 13:22:38,319 [30] INFO  Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - dotnet tool update -g Amazon.Lambda.TestTool-2.1
2022-06-22 13:22:38,319 [30] INFO  Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Tool 'amazon.lambda.testtool-2.1' was reinstalled with the latest stable version (version '0.11.3').

2022-06-22 13:22:38,339 [55] DEBUG Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Lambda Tester already installed: Amazon.Lambda.TestTool-2.1, Project: C:\development\GitHub\FotMob-Poller\AWS\TvSchedulesConcatenator\TvSchedulesConcatenator.csproj
2022-06-22 13:22:38,342 [25] DEBUG Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Lambda Tester already installed: Amazon.Lambda.TestTool-6.0, Project: C:\development\GitHub\FotMob-Poller\AWS\NewsAPI\NewsAPI.csproj
2022-06-22 13:22:38,345 [52] DEBUG Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Lambda Tester already installed: Amazon.Lambda.TestTool-6.0, Project: C:\development\GitHub\FotMob-Poller\AWS\StorageSyncGet\StorageSyncGet.csproj
2022-06-22 13:22:38,347 [50] DEBUG Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Lambda Tester already installed: Amazon.Lambda.TestTool-6.0, Project: C:\development\GitHub\FotMob-Poller\AWS\StorageSyncPut\StorageSyncPut.csproj
2022-06-22 13:22:38,351 [25] DEBUG Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Attempting to install or update Lambda Tester dotnet tool
2022-06-22 13:22:41,529 [43] INFO  Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - dotnet tool update -g Amazon.Lambda.TestTool-3.1
2022-06-22 13:22:41,529 [43] INFO  Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - 
2022-06-22 13:22:41,676 [28] DEBUG Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Lambda Tester already installed: Amazon.Lambda.TestTool-3.1, Project: C:\development\GitHub\FotMob-Poller\AWS\PubDbApi\PubDbApi.csproj
2022-06-22 13:22:41,908 [55] DEBUG Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Lambda Tester already installed: Amazon.Lambda.TestTool-3.1, Project: C:\development\GitHub\FotMob-Poller\AWS\OptaLtcReceiverS3\OptaLtcReceiverS3.csproj
2022-06-22 13:22:41,994 [55] DEBUG Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Lambda Tester already installed: Amazon.Lambda.TestTool-3.1, Project: C:\development\GitHub\FotMob-Poller\AWS\MatchesAPI\MatchesAPI.csproj
2022-06-22 13:22:42,460 [1] ERROR Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterUtilities - Error configuring Lambda Tester on project. FileName: , FullName: , UniqueName: <MiscFiles>
System.Exception: Unable to determine project FileName
   at Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterUtilities.<EnsureLambdaTesterConfiguredAsync>d__2.MoveNext()
2022-06-22 13:22:42,462 [53] DEBUG Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterUtilities - Finished configuring Solution with Lambda Tester
2022-06-22 13:24:13,943 [1] DEBUG Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterUtilities - Configuring Solution with Lambda Tester
2022-06-22 13:24:17,467 [61] DEBUG Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Lambda Tester already installed: Amazon.Lambda.TestTool-6.0, Project: C:\development\GitHub\FotMob-Poller\ElasticSearch\SearchAndSuggest\SearchAndSuggest.csproj
2022-06-22 13:24:18,119 [63] DEBUG Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Lambda Tester already installed: Amazon.Lambda.TestTool-6.0, Project: C:\development\GitHub\FotMob-Poller\AWS\AutoS3VideoTranscoding\AutoS3VideoTranscoding.csproj
2022-06-22 13:24:18,168 [11] DEBUG Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Lambda Tester already installed: Amazon.Lambda.TestTool-2.1, Project: C:\development\GitHub\FotMob-Poller\AWS\ImpressionTracker\ImpressionTracker.csproj
2022-06-22 13:24:18,230 [63] DEBUG Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Lambda Tester already installed: Amazon.Lambda.TestTool-6.0, Project: C:\development\GitHub\FotMob-Poller\AWS\TvSchedulesConcatenator\TvSchedulesConcatenator.csproj
2022-06-22 13:24:18,278 [25] DEBUG Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Lambda Tester already installed: Amazon.Lambda.TestTool-6.0, Project: C:\development\GitHub\FotMob-Poller\AWS\NewsAPI\NewsAPI.csproj
2022-06-22 13:24:18,310 [11] DEBUG Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Lambda Tester already installed: Amazon.Lambda.TestTool-6.0, Project: C:\development\GitHub\FotMob-Poller\AWS\StorageSyncGet\StorageSyncGet.csproj
2022-06-22 13:24:18,326 [63] DEBUG Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Lambda Tester already installed: Amazon.Lambda.TestTool-6.0, Project: C:\development\GitHub\FotMob-Poller\AWS\StorageSyncPut\StorageSyncPut.csproj
2022-06-22 13:24:18,428 [44] DEBUG Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Lambda Tester already installed: Amazon.Lambda.TestTool-6.0, Project: C:\development\GitHub\FotMob-Poller\AWS\PubApi\PubApi.csproj
2022-06-22 13:24:18,484 [25] DEBUG Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Lambda Tester already installed: Amazon.Lambda.TestTool-6.0, Project: C:\development\GitHub\FotMob-Poller\AWS\PubDbApi\PubDbApi.csproj
2022-06-22 13:24:18,676 [63] DEBUG Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Lambda Tester already installed: Amazon.Lambda.TestTool-6.0, Project: C:\development\GitHub\FotMob-Poller\AWS\OptaLtcReceiverS3\OptaLtcReceiverS3.csproj
2022-06-22 13:24:18,692 [62] DEBUG Amazon.AWSToolkit.Lambda.Util.LambdaTesterInstaller - Lambda Tester already installed: Amazon.Lambda.TestTool-6.0, Project: C:\development\GitHub\FotMob-Poller\AWS\MatchesAPI\MatchesAPI.csproj
2022-06-22 13:24:19,024 [1] ERROR Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterUtilities - Error configuring Lambda Tester on project. FileName: , FullName: , UniqueName: <MiscFiles>
System.Exception: Unable to determine project FileName
   at Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterUtilities.<EnsureLambdaTesterConfiguredAsync>d__2.MoveNext()
2022-06-22 13:24:19,025 [44] DEBUG Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterUtilities - Finished configuring Solution with Lambda Tester
2022-06-22 13:24:35,573 [1] INFO  Amazon.AwsToolkit.VsSdk.Common.VSWebProjectInfo - EnvDTEProject.FullName lookup yielded 'C:\development\GitHub\FotMob-Poller\WebAdmin\WebAdmin\WebAdmin.csproj'
2022-06-22 13:24:35,640 [1] INFO  Amazon.AWSToolkit.S3FileFetcher - Null/empty hosted files location override
2022-06-22 13:24:35,642 [1] INFO  Amazon.AWSToolkit.S3FileFetcher - Null/empty hosted files location override
2022-06-22 13:24:35,642 [1] INFO  Amazon.AWSToolkit.S3FileFetcher - Probing for hosted file at url 'https://d3rrggjwfhwld2.cloudfront.net/CloudFormationTemplates/TemplatesManifest.xml'
2022-06-22 13:24:58,503 [62] DEBUG Amazon.AWSToolkit.Telemetry.Internal.TelemetryPublisher - Publishing 2 event(s)
2022-06-22 13:25:06,469 [19] INFO  Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage - Publishing 'WebAdmin' to Amazon Web Services
2022-06-22 13:25:52,850 [32] INFO  Amazon.AWSToolkit.ElasticBeanstalk.Commands.BaseBeanstalkDeployCommand - Publish to AWS Elastic Beanstalk environment 'WheelApiVpc-prod' completed successfully
2022-06-22 13:25:54,197 [54] INFO  Amazon.AWSToolkit.CommonUI.BaseAWSControl - Beginning loading data for EnvStatuse-fsaefapqwm
2022-06-22 13:25:56,008 [54] INFO  Amazon.AWSToolkit.CommonUI.BaseAWSControl - Data loaded data for EnvStatuse-fsaefapqwm
2022-06-22 13:29:58,863 [90] DEBUG Amazon.AWSToolkit.Telemetry.Internal.TelemetryPublisher - Publishing 2 event(s)
2022-06-22 13:30:41,733 [1] INFO  Amazon.AwsToolkit.VsSdk.Common.VSWebProjectInfo - EnvDTEProject.FullName lookup yielded 'C:\development\GitHub\FotMob-Poller\WebAdmin\WebAdmin\WebAdmin.csproj'
2022-06-22 13:30:41,762 [1] INFO  Amazon.AWSToolkit.S3FileFetcher - Null/empty hosted files location override
2022-06-22 13:30:41,762 [1] INFO  Amazon.AWSToolkit.S3FileFetcher - Loading hosted file 'CloudFormationTemplates/TemplatesManifest.xml' from local path 'C:\Users\norapps\AppData\Local/AWSToolkit/downloadedfiles/CloudFormationTemplates/TemplatesManifest.xml'
2022-06-22 13:31:14,775 [100] INFO  Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage - Publishing 'WebAdmin' to Amazon Web Services
2022-06-22 13:31:45,878 [87] INFO  Amazon.AWSToolkit.ElasticBeanstalk.Commands.BaseBeanstalkDeployCommand - Publish to AWS Elastic Beanstalk environment 'WebAdminVPC-prod' completed successfully
2022-06-22 13:31:46,990 [114] INFO  Amazon.AWSToolkit.CommonUI.BaseAWSControl - Beginning loading data for EnvStatuse-rriig3zaax
2022-06-22 13:31:48,966 [114] INFO  Amazon.AWSToolkit.CommonUI.BaseAWSControl - Data loaded data for EnvStatuse-rriig3zaax
2022-06-22 13:34:59,672 [114] DEBUG Amazon.AWSToolkit.Telemetry.Internal.TelemetryPublisher - Publishing 3 event(s)
2022-06-22 13:44:22,693 [15] DEBUG Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Starting a deployment session
2022-06-22 13:44:26,748 [1] DEBUG Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Deployment session started
2022-06-22 13:44:27,037 [124] DEBUG Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Republish targets found for WebAdmin: 0
2022-06-22 13:44:27,038 [95] DEBUG Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Publish targets found for WebAdmin: 3
2022-06-22 13:44:27,782 [120] ERROR Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Error setting deployment target
HTTP Response: 

{"ErrorCode":"UnexpectedError","Message":"Source sequence doesn\u0027t contain any elements.","ProcessExitCode":null}

AWS.Deploy.ServerMode.Client.ApiException: The HTTP status code of the response was not expected (500).

Status: 500
Response: 
{"ErrorCode":"UnexpectedError","Message":"Source sequence doesn\u0027t contain any elements.","ProcessExitCode":null}
   at AWS.Deploy.ServerMode.Client.RestAPIClient.<SetDeploymentTargetAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<InvokeSetDeploymentTargetAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<SetDeploymentTargetAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<SetDeploymentTargetAsync>d__188.MoveNext()
2022-06-22 13:44:27,786 [120] ERROR Amazon.AWSToolkit.Publish.Views.PublishToAwsDocumentControl - Error reloading configuration details
HTTP Response: 

{"ErrorCode":"UnexpectedError","Message":"Source sequence doesn\u0027t contain any elements.","ProcessExitCode":null}

AWS.Deploy.ServerMode.Client.ApiException: The HTTP status code of the response was not expected (500).

Status: 500
Response: 
{"ErrorCode":"UnexpectedError","Message":"Source sequence doesn\u0027t contain any elements.","ProcessExitCode":null}
   at AWS.Deploy.ServerMode.Client.RestAPIClient.<SetDeploymentTargetAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<InvokeSetDeploymentTargetAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<SetDeploymentTargetAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<SetDeploymentTargetAsync>d__188.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Views.PublishToAwsDocumentControl.<ReloadTargetConfigurationsAsync>d__41.MoveNext()
2022-06-22 13:44:29,829 [130] ERROR Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Error setting deployment target
HTTP Response: 

{"ErrorCode":"UnexpectedError","Message":"Source sequence doesn\u0027t contain any elements.","ProcessExitCode":null}

AWS.Deploy.ServerMode.Client.ApiException: The HTTP status code of the response was not expected (500).

Status: 500
Response: 
{"ErrorCode":"UnexpectedError","Message":"Source sequence doesn\u0027t contain any elements.","ProcessExitCode":null}
   at AWS.Deploy.ServerMode.Client.RestAPIClient.<SetDeploymentTargetAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<InvokeSetDeploymentTargetAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<SetDeploymentTargetAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<SetDeploymentTargetAsync>d__188.MoveNext()
2022-06-22 13:44:29,829 [130] ERROR Amazon.AWSToolkit.Publish.Views.PublishToAwsDocumentControl - Error reloading configuration details
HTTP Response: 

{"ErrorCode":"UnexpectedError","Message":"Source sequence doesn\u0027t contain any elements.","ProcessExitCode":null}

AWS.Deploy.ServerMode.Client.ApiException: The HTTP status code of the response was not expected (500).

Status: 500
Response: 
{"ErrorCode":"UnexpectedError","Message":"Source sequence doesn\u0027t contain any elements.","ProcessExitCode":null}
   at AWS.Deploy.ServerMode.Client.RestAPIClient.<SetDeploymentTargetAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<InvokeSetDeploymentTargetAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<SetDeploymentTargetAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<SetDeploymentTargetAsync>d__188.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Views.PublishToAwsDocumentControl.<ReloadTargetConfigurationsAsync>d__41.MoveNext()
2022-06-22 13:44:40,451 [127] DEBUG Amazon.AWSToolkit.Telemetry.Internal.TelemetryPublisher - Publishing 5 event(s)
2022-06-22 13:44:49,900 [1] ERROR Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Failed to update configuration details.
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.SelectMany[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<ApplyConfigSettingsAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<SetTargetConfigurationsAsync>d__197.MoveNext()
2022-06-22 13:44:49,900 [1] ERROR Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Failed to validate configuration details.
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.SelectMany[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<ApplyConfigSettingsAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<SetTargetConfigurationsAsync>d__197.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<ValidateTargetConfigurationsAsync>d__185.MoveNext()
2022-06-22 13:44:49,900 [1] ERROR Amazon.AWSToolkit.Publish.Commands.PublishCommand - Publish to AWS failed: Value cannot be null.
Parameter name: source
System.Exception: Publish to AWS failed: Value cannot be null.
Parameter name: source ---> System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.SelectMany[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<ApplyConfigSettingsAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<SetTargetConfigurationsAsync>d__197.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<ValidateTargetConfigurationsAsync>d__185.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Commands.PublishCommand.<ExecuteCommandAsync>d__7.MoveNext()
   --- End of inner exception stack trace ---
2022-06-22 13:45:08,592 [130] ERROR Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Error setting deployment target
HTTP Response: 

{"ErrorCode":"UnexpectedError","Message":"Source sequence doesn\u0027t contain any elements.","ProcessExitCode":null}

AWS.Deploy.ServerMode.Client.ApiException: The HTTP status code of the response was not expected (500).
```

**Comment by awschristou** [comment]
Version 1.35.2.0 of the Toolkit is now available, containing some fixes to issues preventing Publish to AWS from starting or performing a publish. Please try this new version, and file a new issue if you continue to experience difficulties publishing.
