### ISSUE TITLE
Error attempting to debug: "Read-only file system: '.aws-sam'"

### ISSUE THREAD

**Issue by ryancabanas** [aws/aws-toolkit-visual-studio#269]
I'm not sure if this is the right place to ask this, but I figured I'd start here.

When trying to debug my API, I get the following error:

> OSError: [Errno 30] Read-only file system: '.aws-sam'

Here are the details of my installation.

> OS: Darwin arm64 21.5.0
Visual Studio Code extension host:  1.69.0
AWS Toolkit:  1.45.0
node: 16.13.2
electron: 18.3.5

Here's some additional details I saw from the output right before the error message:

> 2022-07-11 12:46:10 [INFO]: 2022-07-11 12:46:10,847 | NodejsNpmBuilder:NpmInstall succeeded
>
> 2022-07-11 12:46:10 [INFO]: 2022-07-11 12:46:10,848 | Running NodejsNpmBuilder:CleanUp
> 2022-07-11 12:46:10,848 | Clean up action: .aws-sam/deps/f3cf6ba2-a66b-4ad2-9d6d-b4e2e4f91a5d does not exist and will be skipped.
2022-07-11 12:46:10,848 | NodejsNpmBuilder:CleanUp succeeded
2022-07-11 12:46:10,848 | Running NodejsNpmBuilder:CopyDependencies
2022-07-11 12:46:10,848 | Creating target folders at .aws-sam/deps/f3cf6ba2-a66b-4ad2-9d6d-b4e2e4f91a5d/node_modules
>
> 2022-07-11 12:46:10 [INFO]: 2022-07-11 12:46:10,848 | NodejsNpmBuilder:CopyDependencies raised unhandled exception
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.53.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 301, in run
    action.execute()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.53.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/actions.py", line 132, in execute
    copytree(dependencies_source, new_destination)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.53.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/utils.py", line 46, in copytree
    os.makedirs(destination)
  File "/opt/homebrew/Cellar/python@3.8/3.8.13_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/homebrew/Cellar/python@3.8/3.8.13_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/homebrew/Cellar/python@3.8/3.8.13_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/homebrew/Cellar/python@3.8/3.8.13_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '.aws-sam'
>
> 2022-07-11 12:46:10 [INFO]: 
Build Failed
>
> 2022-07-11 12:46:10 [INFO]: 2022-07-11 12:46:10,854 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '9154515c-5cb9-4eeb-9cb2-df5e1f276ff8', 'installationId': 'f35fb38d-ea04-4a79-8491-7aaa3602a52c', 'sessionId': '38c451aa-3e4a-4319-b78c-832e10cf171d', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.13', 'samcliVersion': '1.53.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'metricSpecificAttributes': {'projectType': 'CFN'}, 'duration': 1720, 'exitReason': 'WorkflowUnknownError', 'exitCode': 1}}]}
>
> 2022-07-11 12:46:11 [INFO]: 2022-07-11 12:46:11,294 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
>
> 2022-07-11 12:46:11 [INFO]: Error: NodejsNpmBuilder:CopyDependencies - [Errno 30] Read-only file system: '.aws-sam'

Debugging was working for me in the past.  I recently updated `aws-sam-cli` to `1.53.0`, but I don't know if this is the issue because `brew` removed the previous version when upgrading.  😞  *(I think I have this successfully disabled now, but too late for testing this issue.)*

Any ideas on what I should check/try?

Thank you!

**Comment by ryancabanas** [comment]
Hi @JadenSimon 
Oh shoot!  Sorry about that!  Thanks for the link and sam re-installation suggestion!
