### ISSUE TITLE
Issue while deploying ASP.Net Core Project on AWS Elasticbeanstalk

### ISSUE THREAD

**Issue by Satyajust4p** [aws/aws-toolkit-visual-studio#309]
Step 1:- I created a simple ASP.Net Core Web App using Visual Studio 2022
Step 2:- Installed AWS toolkit
Step3:- Selected Publish to AWS for deploying my application on my free AWS tier using Elasticbeanstalk
Step 4:- I get the following error on the 3rd Step i.e. on Deploying AWS CDK Project :
                 
AWSDeploymentProject: deploying...
[0%] start: Publishing 73645f7c905524d6ca666eae7e1e2a7f1bca1d4062451cd2eb619d2d2f7ec4ec:712088662267-eu-central-1
[0%] start: Publishing b634beaf9192c9e30537653615f0e0f9c3d21b3ab410d6ca555b2ea7fd8ce062:712088662267-eu-central-1
[50%] fail: Socket timed out without establishing a connection
[100%] fail: Socket timed out without establishing a connection

 ❌  AWSDeploymentProject failed: Error: Failed to publish one or more assets. See the error messages above for more information.
    at publishAssets (C:\Users\ssaty\AppData\Local\npm-cache\_npx\e72b144743208263\node_modules\aws-cdk\lib\util\asset-publishing.ts:60:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CloudFormationDeployments.publishStackAssets (C:\Users\ssaty\AppData\Local\npm-cache\_npx\e72b144743208263\node_modules\aws-cdk\lib\api\cloudformation-deployments.ts:572:7)
    at CloudFormationDeployments.deployStack (C:\Users\ssaty\AppData\Local\npm-cache\_npx\e72b144743208263\node_modules\aws-cdk\lib\api\cloudformation-deployments.ts:419:7)
    at deployStack2 (C:\Users\ssaty\AppData\Local\npm-cache\_npx\e72b144743208263\node_modules\aws-cdk\lib\cdk-toolkit.ts:264:24)
    at C:\Users\ssaty\AppData\Local\npm-cache\_npx\e72b144743208263\node_modules\aws-cdk\lib\deploy.ts:39:11
    at run (C:\Users\ssaty\AppData\Local\npm-cache\_npx\e72b144743208263\node_modules\p-queue\dist\index.js:163:29)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: Failed to publish one or more assets. See the error messages above for more information.
    at deployStacks (C:\Users\ssaty\AppData\Local\npm-cache\_npx\e72b144743208263\node_modules\aws-cdk\lib\deploy.ts:61:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CdkToolkit.deploy (C:\Users\ssaty\AppData\Local\npm-cache\_npx\e72b144743208263\node_modules\aws-cdk\lib\cdk-toolkit.ts:338:7)
    at initCommandLine (C:\Users\ssaty\AppData\Local\npm-cache\_npx\e72b144743208263\node_modules\aws-cdk\lib\cli.ts:364:12)

Stack Deployments Failed: Error: Failed to publish one or more assets. See the error messages above for more information.

AWSDeploymentProject could not be published as ASP.NET Core App to AWS Elastic Beanstalk on Windows: We had an issue deploying your application to AWS. Check the deployment output for more details. Deployment took 124.84s.
AWSDeploymentProject failed to publish to AWS.

Note : The IAM user has administrator privileges.

Any help would be appreciated.

**Comment by Satyajust4p** [comment]
> Hi @Satyajust4p , are you deploying to a VPC? If so, does the deployment work if you deploy without a VPC?
Thanks @awschristou  for the reply.First I didnt select any particular VPN while deploying, but in the later attempts I tried deploying with the custom VPN that has an internet gateway but still getting the same error. However if i create an environment through Elastic Beanstalk console and deploy my project through Visual Studio it does work but if i publish to the new environment it fails. 

I am unable to understand my fault.

**Comment by Satyajust4p** [comment]
> Hi @Satyajust4p - can you post your Node and CDK versions? (if you have CDK installed globally as opposed to relying on the Visual Studio Toolkit to install it for you)
> 
> ```
> node --version
> cdk --version
> ```
> 
> [aws/aws-cdk#19930](https://github.com/aws/aws-cdk/issues/19930) has a similar error message and some recent activity over on the CDK repo, hunch it may be related.

Thanks @ashovlin for the reply. 

Here is the node version : v16.14.0. 
cdk version i get error : 'cdk' is not recognized as an internal or external command,operable program or batch file

**Comment by ashovlin** [comment]
I've created https://github.com/aws/aws-dotnet-deploy/issues/755 to track this issue on the .NET deploy tool repo. The Visual Studio Toolkit wraps the deploy tool, which is responsible for the CDK deployment. Any guidance/fix will likely apply to the deploy tool layer.

**Comment by ashishdhingra** [comment]
@Satyajust4p Good morning. Could you please share the following:
- Sample code solution along with the reproduction steps
- Deployment environment
-  Also confirm if any other AWS related deployments are having issue, may be due to network rules. The error message indicates socket timeout error.

Thanks,
Ashish

**Comment by LeoRodaelli** [comment]
Do you solved this issue?

**Comment by awschristou** [comment]
This issue has grown stale. Without additional steps to reproduce or supporting details, we aren't able to investigate this issue further. If you are still encountering this problem, please open a new issue and provide supporting details.
