### ISSUE TITLE
Profiles setup under C:\Users\<username>\.aws\credentials are not listed in the AWS Explorer window under "credentials"

### ISSUE THREAD

**Issue by gamelover42** [aws/aws-toolkit-visual-studio#324]
**Describe the bug**
Profiles setup under C:\Users\<username>\\.aws\credentials are not listed in the AWS Explorer window under "credentials"

**To Reproduce**
1. Add a profile to "foo" C:\Users\<username>\\.aws\credentials including the aws_access_key_id and aws_secret_access_key
2. Install Visual Studio 2022
3. Install AWS Toolkit for Visual Studio 2022
4. Note that the "foo" profile is not listed in the AWS Explorer window "credentials" list
5. Click "add new profile" button
6. enter "foo" as the profile name, along with other information
7. Note that the "foo" profile in C:\Users\<username>\\.aws\credentials will be updated however the "credentials" list in the AWS Explorer window is still empty.

**Expected behavior**
AWS profiles in C:\Users\<username>\\.aws\credentials will display in the AWS Explorer window "credentials" list

**Computer (please complete the following information):**

- Windows Version: Windows 10 Enterprise 20H2 (19042.2604)
- Visual Studio Version: Visual Studio Enterprise 2022 Version 17.5.1
- AWS Toolkit for Visual Studio Version: 1.39.0

**Comment by floralph** [comment]
Thank you for bringing this issue to our attention.  I am unable to reproduce this issue with the steps provided.  To help us further research this problem, please post the `[foo]` section that you added to your C:\Users<username>\.aws\credentials file.  **Be sure to redact/remove the actual credential values before posting.**

Also, check the toolkit logs (from the VS main menu, click Extensions / AWS Toolkit / View Toolkit Logs) for pertinent messages.  You can case-insensitive search for "credential" in the log to find these.   Please post your log output in the issue.

**Comment by rbbarad** [comment]
Hi @gamelover42, we haven't been able to reproduce this. Could you please share the above items from @floralph's comment to help us investigate this further?

**Comment by gamelover42** [comment]
here's my credentials file:
[default]
aws_access_key_id = <access key here>
aws_secret_access_key = <secret key here>


The toolkit logs have some errors. 
2023-04-03 09:22:05,986 [24] INFO  Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage - AWSToolkitPackage InitializeAsync started
2023-04-03 09:22:06,096 [14] DEBUG Amazon.AWSToolkit.Telemetry.TelemetryService - Telemetry service enabled
2023-04-03 09:22:06,102 [14] INFO  Amazon.AWSToolkit.ResourceFetchers.FileResourceFetcher - Loading resource: C:\Users\dnelson\AppData\Local/AWSToolkit\downloadedfiles\endpoints.json
2023-04-03 09:22:06,115 [6] DEBUG Amazon.AWSToolkit.VisualStudio.Telemetry.TelemetryManager - Initializing Telemetry Service
2023-04-03 09:22:06,116 [6] ERROR Amazon.AWSToolkit.VisualStudio.Telemetry.TelemetryManager - Error during TelemetryManager initialization
System.TypeLoadException: Could not load type 'Amazon.Runtime.IDefaultConfiguration' from assembly 'AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'.
   at Amazon.CognitoIdentity.AmazonCognitoIdentityConfig..ctor()
   at Amazon.CognitoIdentity.CognitoAWSCredentials..ctor(String accountId, String identityPoolId, String unAuthRoleArn, String authRoleArn, RegionEndpoint region) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Services\CognitoIdentity\Custom\CognitoAWSCredentials.cs:line 491
   at Amazon.AWSToolkit.VisualStudio.Telemetry.TelemetryManager.Initialize()
2023-04-03 09:22:06,164 [8] INFO  Amazon.AWSToolkit.ResourceFetchers.FileResourceFetcher - Loading resource: C:\Users\dnelson\AppData\Local/AWSToolkit\downloadedfiles\endpoints.json
2023-04-03 09:22:06,178 [8] INFO  Amazon.AWSToolkit.ResourceFetchers.HttpResourceFetcher - Loading resource: https://idetoolkits.amazonwebservices.com/endpoints.json
2023-04-03 09:22:06,507 [5] DEBUG Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage - Creating SAWSToolkitShellProvider service
2023-04-03 09:22:06,592 [12] INFO  Amazon.AWSToolkit.Credentials.Core.ProfileCredentialProviderFactory - Reloaded AWS Credential Profiles
Profiles found: 1
2023-04-03 09:22:06,592 [12] ERROR Amazon.AWSToolkit.Credentials.Core.ProfileCredentialProviderFactory - The following credentials could not be loaded: 
default: Method not found: 'Boolean Amazon.Runtime.Internal.Util.ProfileIniFile.TryGetSection(System.String, Boolean, System.Collections.Generic.Dictionary`2<System.String,System.String> ByRef)'.
2023-04-03 09:22:06,698 [17] DEBUG Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage - Setting up Publish to AWS functionality
2023-04-03 09:22:06,720 [30] DEBUG Amazon.AWSToolkit.Publish.Package.PublishToAwsPackage - Initializing PublishToAws Package

**Comment by awschristou** [comment]
Thank you @gamelover42 , based on the error `Method not found: 'Boolean Amazon.Runtime.Internal.Util.ProfileIniFile.TryGetSection`, it looks like the Toolkit is trying to use an older version of the AWS SDK than the one it shipped with. There are some steps that can help diagnose this written in https://github.com/aws/aws-toolkit-visual-studio/issues/138#issuecomment-756930669 and https://github.com/aws/aws-toolkit-visual-studio/issues/138#issuecomment-758314113. Would you be able to to try that out and share your findings?

**Comment by awschristou** [comment]
Thanks for the follow up - glad to hear it is working for you
