### ISSUE TITLE
Receiving a HTTP 500 error when trying to deploy to Ireland and London Region

### ISSUE THREAD

**Issue by cmcbride781** [aws/aws-toolkit-visual-studio#338]
**Describe the bug**
I am in the process of trying to deploy a .Net Core Application using ElasticBeanstalk however in "Publish to New Target Screen" I receive "A error occured in the deployment tool"

I have gone through the AWS tool kit log and scene the following:

2023-04-25 11:55:07,623 [26] DEBUG Amazon.AWSToolkit.Telemetry.Internal.TelemetryPublisher - Publishing 8 event(s)
2023-04-25 11:59:32,793 [76] DEBUG Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Stopping a deployment session
2023-04-25 11:59:32,798 [32] DEBUG Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Deployment session stopped
2023-04-25 11:59:32,799 [52] DEBUG Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Starting a deployment session
2023-04-25 12:00:05,683 [1] DEBUG Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Deployment session started
2023-04-25 12:00:05,701 [76] DEBUG Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Republish targets found for CBW.UI: 0
2023-04-25 12:00:05,702 [26] DEBUG Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel - Publish targets found for CBW.UI: 4
2023-04-25 12:00:07,928 [76] DEBUG Amazon.AWSToolkit.Telemetry.Internal.TelemetryPublisher - Publishing 3 event(s)
2023-04-25 12:00:21,635 [61] ERROR Amazon.AWSToolkit.Publish.Views.PublishToAwsDocumentControl - Error reloading configuration details
Amazon.AWSToolkit.Publish.DeployToolException: Deploy Tool failed due to internal error. ---> AWS.Deploy.ServerMode.Client.ApiException: The HTTP status code of the response was not expected (500).

Status: 500
Response: 
{"ErrorCode":"FailedToFindElasticBeanstalkSolutionStack","Message":"Cannot use Elastic Beanstalk deployments because we cannot find a .NET Core Solution Stack to use. One possible reason could be that Elastic Beanstalk is not enabled in your region if you are using a non-default region.","ProcessExitCode":null}
   at AWS.Deploy.ServerMode.Client.RestAPIClient.<SetDeploymentTargetAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<InvokeSetDeploymentTargetAsync>d__23.MoveNext()
   --- End of inner exception stack trace ---
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<InvokeSetDeploymentTargetAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<SetDeploymentTargetAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<SetDeploymentTargetAsync>d__182.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<SetDeploymentTargetAsync>d__182.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Views.PublishToAwsDocumentControl.<ReloadTargetConfigurationsAsync>d__41.MoveNext()

I have gone back through and ensured that no 403 forbiddens are occuring. 

**To Reproduce**
Right click on application > Publish to AWS

About Info:
Microsoft Visual Studio Professional 2022
Version 17.5.4
VisualStudio.17.Release/17.5.4+33530.505
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Professional

ASP.NET and Web Tools   17.5.318.41597
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.5.318.41597
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.5.318.41597
Azure Functions and Web Jobs Tools

C# Tools   4.5.2-3.23171.7+d17f741546fad2786cbd6394d08619544e53a36d
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.5.2.2316603+9f1b6856460af1e592d387ebef416eadddac453f
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.2.40120.0
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.20105.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.5.2-3.23171.7+d17f741546fad2786cbd6394d08619544e53a36d
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.5.0-beta.23053.5+794b7c259d9646a7eb685dad865aa27da7940a21
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

![image](https://user-images.githubusercontent.com/75982775/234259729-a56daacd-a747-43a8-815d-37d1f010ff6d.png)

**Comment by awschristou** [comment]
Hi @cmcbride781 , thank you for providing some log details. Can you see what version of the Toolkit you are using? When you launch Visual Studio, open the "View" menu and select "Output". Then select to show output from "Amazon Web Services". The top of this particular output pane should show an entry like this (the second line is the one of interest):

```
08:30:53:374	AWS Toolkit for Visual Studio
08:30:53:374	Toolkit Version: 1.40.0.0
08:30:53:374	Visual Studio: VS Professional 2022, Version: 17.5.2
```

**Comment by cmcbride781** [comment]
The @awschristou, 

This is the output I get:
AWS Toolkit for Visual Studio
Toolkit Version: 1.40.0.0
Visual Studio: VS Professional 2022, Version: 17.5.1

**Comment by awschristou** [comment]
Ok, it looks like you are using the current version of the Toolkit. I wanted to rule that out.

A couple of things to try:

## Install the .net deploy tool and try running it from the command line

I'd like to know if you get the same behavior directly from the deploy tooling.

From the command line, run `dotnet tool install -g aws.deploy.tools` . Then change directories into the folder containing your project (csproj file). Run `dotnet aws deploy` , and work through the prompts to try to deploy to Beanstalk on Linux in the Ireland region. (usage details can be found at https://aws.github.io/aws-dotnet-deploy/ )

Does this proceed, or does it produce a similar error? 

## Allow the Toolkit to re-download the deploy tool

I'd like to rule out whether or not the Toolkit was holding on to an older version of the deploy tool.

Close all of your running Visual Studio instances. Open the folder `%localappdata%\AWSToolkit\aws.deploy.tools` and delete the contents of this filter. Re-launch Visual Studio, and allow the AWS Toolkit to re-install its copy of the .NET deploy tool. Try to perform your deployment again.

Does this proceed, or does it produce a similar error?
