### ISSUE TITLE
AWS Explorer can't read credentials file correctly because of a comment in ini file

### ISSUE THREAD

**Issue by mmegel-biontech** [aws/aws-toolkit-visual-studio#354]
**Describe the bug**
AWS Explorer don't show any profile or allow to add new profiles.

**To Reproduce**

1. Add a comment to your AWS `credentials` file like:
   ```
   [default] # some comment
   account_id=...
   region=...
   
   # ...
   ```
1. Open VS2022 and navigate to AWS Explorer

**Expected behavior**
The AWS Explorer should show the profiles.

**Screenshots**
No profile is available in AWS Explorer:
<img width="246" alt="image" src="https://github.com/aws/aws-toolkit-visual-studio/assets/132681997/5afe7f5b-4d12-449c-b6de-eee401f53a70">

But, AWS CLI have already some profiles:
<img width="340" alt="image" src="https://github.com/aws/aws-toolkit-visual-studio/assets/132681997/1171229a-41fd-460f-815c-5e7d743c3028">

**Error Logs:**

```
2023-08-14 07:36:35,752 [30] INFO  Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage - AWSToolkitPackage InitializeAsync started
2023-08-14 07:36:37,820 [6] DEBUG Amazon.AWSToolkit.Telemetry.TelemetryService - Telemetry service enabled
2023-08-14 07:36:37,825 [6] INFO  Amazon.AWSToolkit.ResourceFetchers.FileResourceFetcher - Loading resource: C:\Users\micha\AppData\Local/AWSToolkit\downloadedfiles\endpoints.json
2023-08-14 07:36:37,828 [8] DEBUG Amazon.AWSToolkit.VisualStudio.Telemetry.TelemetryManager - Initializing Telemetry Service
2023-08-14 07:36:37,878 [19] INFO  Amazon.AWSToolkit.ResourceFetchers.FileResourceFetcher - Loading resource: C:\Users\micha\AppData\Local/AWSToolkit\downloadedfiles\endpoints.json
2023-08-14 07:36:37,891 [8] ERROR Amazon.AWSToolkit.VisualStudio.Telemetry.TelemetryManager - Error during TelemetryManager initialization
System.TypeInitializationException: The type initializer for 'Amazon.Runtime.Internal.FallbackInternalConfigurationFactory' threw an exception. ---> System.IO.InvalidDataException: Line 11:<[default] # BNT
> in file C:\Users\micha\.aws\credentials does not contain a section, property or comment.
   at Amazon.Runtime.Internal.Util.IniFile.Validate() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\IniFile.cs:line 437
   at Amazon.Runtime.CredentialManagement.SharedCredentialsFile.Refresh() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\CredentialManagement\SharedCredentialsFile.cs:line 468
   at Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain.TryGetProfile(String profileName, CredentialProfile& profile) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\CredentialManagement\CredentialProfileStoreChain.cs:line 120
   at Amazon.Runtime.Internal.ProfileInternalConfiguration.Setup(ICredentialProfileSource source, String profileName) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\InternalConfiguration.cs:line 209
   at Amazon.Runtime.Internal.FallbackInternalConfigurationFactory.Reset() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\InternalConfiguration.cs:line 278
   at Amazon.Runtime.Internal.FallbackInternalConfigurationFactory..cctor() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\InternalConfiguration.cs:line 263
   --- End of inner exception stack trace ---
   at Amazon.Runtime.ClientConfig.get_RetryMode() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\ClientConfig.cs:line 836
   at Amazon.Runtime.AmazonServiceClient.BuildRuntimePipeline() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AmazonServiceClient.cs:line 448
   at Amazon.CognitoIdentity.CognitoAWSCredentials..ctor(String accountId, String identityPoolId, String unAuthRoleArn, String authRoleArn, RegionEndpoint region) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Services\CognitoIdentity\Custom\CognitoAWSCredentials.cs:line 491
   at Amazon.AWSToolkit.VisualStudio.Telemetry.TelemetryManager.Initialize()
2023-08-14 07:36:37,897 [19] INFO  Amazon.AWSToolkit.ResourceFetchers.HttpResourceFetcher - Loading resource: https://idetoolkits.amazonwebservices.com/endpoints.json
2023-08-14 07:36:38,061 [12] DEBUG Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage - Creating SAWSToolkitShellProvider service
2023-08-14 07:36:38,444 [9] ERROR Amazon.AWSToolkit.Credentials.Core.ToolkitCredentialInitializer - Error while setting up Shared credentials for the toolkit.
System.IO.InvalidDataException: Line 11:<[default] # some comment
> in file C:\Users\micha\.aws\credentials does not contain a section, property or comment.
   at Amazon.Runtime.Internal.Util.IniFile.Validate() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\IniFile.cs:line 437
   at Amazon.Runtime.CredentialManagement.SharedCredentialsFile.Refresh() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\CredentialManagement\SharedCredentialsFile.cs:line 468
   at Amazon.AWSToolkit.Credentials.Core.ToolkitCredentialInitializer.AddSharedCredentialsFactory()
```

**Computer (please complete the following information):**

- Windows Version: Windows 11 (10.0.22621)
- Visual Studio Version: 2022 Version 17.6.4
- AWS Toolkit for Visual Studio Version: 1.42.0.0

**Additional context**

The problem can be solved by removing the comment from ini file section:

```
# some comment
[default]
account_id=...
region=...

# ...
```

**Comment by mmegel-biontech** [comment]
@justinmk3 I guess not, for that reason I have reported this issue.

**Comment by rbbarad** [comment]
INI file syntax supports comments that exist on a line of their own, but does not support inline commenting. Closing the issue as this is a limitation of the INI file syntax rather than an issue with the Toolkit's credentials file processing.
