### ISSUE TITLE
Unable to use SSO Profiles when running `dotnet restore`

### ISSUE THREAD

**Issue by gwin003** [aws/aws-toolkit-visual-studio#356]
We are migrating from local AWS profiles using access keys and secret keys to IAM Identity Center credentials using SSO. We have our credentials file working, and running commands like `aws s3api list-buckets --query "Buckets[].Name" --profile profile1` are working correctly.

But I am unable to install nuget packages from CodeArtifact using the SSO profiles. Typically we would run `dotnet restore --no-cache` to update our packages, but running this now results in the following error.

`error NU1301: Unable to load the service index for source https://{account}.d.codeartifact.us-east-1.
amazonaws.com/nuget/{accountName}/v3/index.json.`

#200 mentions that SSO profiles are supported, so I'm sure I'm using it wrong. Can anyone point me in the correct direction? TIA

**Comment by awschristou** [comment]
Hi @gwin003 , this repo is related to the AWS Toolkit, which has a CodeArtifact handler. If you have the AWS Toolkit installed, and have configured the CodeArtifact profile to use, are you able to restore and build your projects from Visual Studio? This should prompt you to perform the SSO login flow.

To get things working from the command line, you will want to check out https://docs.aws.amazon.com/codeartifact/latest/ug/nuget-cli.html

**Comment by gwin003** [comment]
Hey @awschristou, sorry about that. Been bouncing around quite a few github repos today. Is there a better place to post this question?

Anyways I've been living on that page you linked without any success. Here's the steps I took...

```powershell
dotnet tool uninstall -g AWS.CodeArtifact.NuGet.CredentialProvider
dotnet tool install -g AWS.CodeArtifact.NuGet.CredentialProvider`
dotnet codeartifact-creds install
aws sso login
aws s3api list-buckets --query "Buckets[].Name" --profile profile1  #this works
aws s3api list-buckets --query "Buckets[].Name" --profile profile2  #this also works
dotnet restore --no-cache                                           #this throws the above error
``` 

I do have the toolkit installed, but I typically use VS Code. I launched Visual Studio and attempted to use the toolkit but it keeps asking for Proxy Authentication to a single AWS Account (not the SSO provider).

**Comment by awschristou** [comment]
@derektam can you advise on a suitable repo for getting help with the CodeArtifact Credential provider?

**Comment by mora260** [comment]
I'm experiencing the same issue. Even when configuring the SSO as the default AWS profile, always get the same error. 

Did you get it to work @gwin003 ?

**Comment by ckaczor** [comment]
I've been hitting this recently as well.  I turned on logging for the credentials plugin and I got:

> 2024/06/06 14:40:34.59 Failed retrieved CodeArtifact auth token System.ArgumentNullException: Value cannot be null. (Parameter 'Property cannot be empty: Region, StartUrl')
   at Amazon.Runtime.SSOAWSCredentials.ValidateCredentialsInputs()
   at Amazon.Runtime.SSOAWSCredentials.GenerateNewCredentialsAsync()
   at Amazon.Runtime.RefreshingAWSCredentials.GetCredentialsAsync()
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at AWS.CodeArtifact.NuGetCredentialProvider.RequestHandlers.GetAuthenticationCredentialsRequestHandler.HandleRequestAsync(GetAuthenticationCredentialsRequest request)

I tried copying the sso_region and sso_start_url lines in the AWS config file from the sso-section to the profile section and the error changed to:

> 2024/06/07 11:38:32.69 Failed retrieved CodeArtifact auth token System.ArgumentNullException: Value cannot be null. (Parameter 'Options property cannot be empty: ClientName')
   at Amazon.Runtime.SSOAWSCredentials.GetSsoCredentialsAsync(ICoreAmazonSSOOIDC oidc, ICoreAmazonSSO sso)
   at Amazon.Runtime.SSOAWSCredentials.GenerateNewCredentialsAsync()
   at Amazon.Runtime.RefreshingAWSCredentials.GetCredentialsAsync()
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at AWS.CodeArtifact.NuGetCredentialProvider.RequestHandlers.GetAuthenticationCredentialsRequestHandler.HandleRequestAsync(GetAuthenticationCredentialsRequest request)

This all works fine if I use a profile with a short-term token but not with SSO.  It also all works when using Visual Studio with the AWS extension.

Is there any solution for this?  Seems like the plugin needs to be updated for recent changes?

Thanks!

**Comment by floralph** [comment]
@detam-amazon can you advise on a suitable repo for getting help with the CodeArtifact Credential provider?

**Comment by sankalpbhandari** [comment]
Hi @ckaczor, I am sorry that you are having issues with the credential provider.
I have few questions for you - 
1. Is it intermittent issue or you always face it when using sso profile?
2. Is the sso profile set as default profile or its a named profile?
3. If its not set as default profile, can you please try setting the profile to be used with credential profile using `dotnet-codeartifact-creds configure set profile <profile_name>`

**Comment by ckaczor** [comment]
Thanks for the reply.  I've never gotten this to work with sso - I've tried with both the default profile and a named profile.

**Comment by sankalpbhandari** [comment]
Hello, we have published the updated version 1.0.2 on nuget.org
https://www.nuget.org/packages/AWS.CodeArtifact.NuGet.CredentialProvider

It should be available for consumption.
