### ISSUE TITLE
'Publish to AWS' Failing - 'Unable to determine deploy tool version, no output was detected'

### ISSUE THREAD

**Issue by ghechtRDI** [aws/aws-toolkit-visual-studio#370]
**Describe the bug**
After successfully connecting AWS Explorer to AWS using IAM credentials, the 'Publish to AWS' action results in an error with no obvious solution. 

**To Reproduce**
- Install latest AWS Toolkit version 
- Project is net7.0
- AWS credentials are working and AWS explorer is populated with data

**Expected behavior**
- 'Publish to AWS' should open publish dialogue

**Screenshots**
![image](https://github.com/aws/aws-toolkit-visual-studio/assets/97562096/77b9819a-06fd-4f07-8428-a544bf0829d9)

**Toolkit Logs**
The logs show the following:
2023-10-16 13:04:30,999 [27] DEBUG Amazon.AWSToolkit.ToolkitFactory - Finished Registering Toolkit Plugins in the AWS Explorer...
2023-10-16 13:04:31,015 [1] DEBUG Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterEventListener - Initializing Lambda Tester event listener
2023-10-16 13:04:31,031 [1] INFO  Amazon.AWSToolkit.ToolkitFactory - ToolkitFactory initialized
2023-10-16 13:04:31,031 [27] INFO  Amazon.AWSToolkit.ToolkitFactory - ToolkitFactory SignalShellInitializationComplete
2023-10-16 13:04:31,031 [26] INFO  Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage - AWSToolkitPackage InitializeAsync complete
2023-10-16 13:04:31,031 [11] INFO  Amazon.AWSToolkit.Utility - Running log cleanup
2023-10-16 13:04:31,358 [15] DEBUG Amazon.AWSToolkit.Telemetry.TelemetryService - Telemetry service enabled
2023-10-16 13:04:50,598 [42] DEBUG Amazon.AWSToolkit.Telemetry.Internal.TelemetryPublisher - Publishing 8 event(s)
2023-10-16 13:04:51,123 [1] INFO  Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage - Received __VSSPROPID2.VSSPROPID_MainWindowVisibility property change, new value True
2023-10-16 13:04:51,123 [1] DEBUG Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage - Toolkit considers VS to be initialized now
2023-10-16 13:04:53,401 [1] DEBUG Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterEventListener - Registering Debugger events
2023-10-16 13:04:53,409 [1] DEBUG Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterUtilities - Configuring Solution with Lambda Tester
2023-10-16 13:04:54,257 [1] ERROR Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterUtilities - Error configuring Lambda Tester on project. FileName: , FullName: , UniqueName: <MiscFiles>
System.Exception: Unable to determine project FileName
   at Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterUtilities.<EnsureLambdaTesterConfiguredAsync>d__2.MoveNext()
2023-10-16 13:04:54,265 [9] DEBUG Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterUtilities - Finished configuring Solution with Lambda Tester
2023-10-16 13:05:06,044 [1] ERROR Amazon.AWSToolkit.Publish.Package.PublishToAws - Failed to open the Publish document
Amazon.AWSToolkit.Publish.DeployToolException: Unable to determine deploy tool version, no output was detected.
   at Amazon.AWSToolkit.Publish.Install.GetCurrentCliVersion.ParseVersionFromCliOutput(String output)
   at Amazon.AWSToolkit.Publish.Install.GetCurrentCliVersion.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Install.DeployCliInstaller.<UpdateIsAvailableAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Install.DeployCliInstaller.<NoUpdateAvailableAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Install.DeployCliInstaller.<InstallAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Install.DeployCli.<InstallDeployCliAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Install.DeployCli.<>c__DisplayClass5_0.<<InstallCliAsync>g__Install|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Telemetry.TelemetryLoggerExtensionMethods.<TimeAndRecordAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Install.DeployCli.<InstallCliAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Install.DeployCli.<InitializeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Package.PublishToAwsPackage.<InitializeDeployCliInBackgroundAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Package.PublishToAws.<WaitForCliInitializationToCompleteAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Package.PublishToAws.<InstallDeployToolAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Package.PublishToAws.<>c__DisplayClass7_0.<<ShowPublishToAwsDocumentAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Amazon.AWSToolkit.Publish.Models.PublishDialogStepProcessor.<ProcessStepsAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Package.PublishToAws.<ShowPublishToAwsDocumentAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Package.PublishToAws.<>c__DisplayClass15_0.<<ShowPublishToAwsDocumentAsync>g__Show|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Telemetry.TelemetryLoggerExtensionMethods.<TimeAndRecordAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Package.PublishToAws.<ShowPublishToAwsDocumentAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.Package.PublishToAws.<ShowPublishToAwsDocumentAsync>d__7.MoveNext()

**Development System (please complete the following information):**
- Windows Version: 10.0.19045 Build 19045
- Visual Studio Version: 17.7.4
- AWS Toolkit for Visual Studio Version: 1.43.0.0

**Comment by ghechtRDI** [comment]
I just updated Visual Studio from Version 117.7.5 and now 'Publish to AWS' is working. Seems like it may have been a VS bug.
