### ISSUE TITLE
AWS Toolkit unable to install Codewhisper extension on visual studio and after trying uninstall and reinstall Aws Toolkit is no longer installing

### ISSUE THREAD

**Issue by SamRD2** [aws/aws-toolkit-visual-studio#386]
**Computer (please complete the following information):**

- Windows Version:
- 11
- Visual Studio Version:
- Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.6.0
- AWS Toolkit for Visual Studio Version:
Taken from here today: https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.AWSToolkitforVisualStudio2022

**Install log**
26/01/2024 10:23:29 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
26/01/2024 10:23:29 - 		Name         : Visual Studio core editor
26/01/2024 10:23:29 - 		Version      : [17.7,18.0)
26/01/2024 10:23:29 - Signature Details...
26/01/2024 10:23:29 - 	Extension is signed with a valid signature.
26/01/2024 10:23:29 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& 
skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   
**Any other information**
Going to Extensions -> Manage extensions -> searching for AWS, no longer returns AWS Toolkit. It is only available in the Roaming extension manager, but this returns nothing useful.

**Comment by SamRD2** [comment]
I was able to resolve this issue, by upgrading Visual Studio to version 17.8. 
There was a minor issue logged on the install of 17.8, but it doesn't seem to cause any issues.

**Comment by SamRD2** [comment]
Actually the following issue is causing Visual studio not to work (even though I can install Codewhisperer for it now):
Couldn't install Microsoft.visualCpp.Redist.14

**Comment by SamRD2** [comment]
I was able to resolve this, through multiple uninstalls and reinstalls and installing the redist separately and restarting machine.

**Comment by awschristou** [comment]
Thank you for reaching out. The Toolkit now requires 17.7 or later of Visual Studio, see https://github.com/aws/aws-toolkit-visual-studio/issues/375 for details. I will close this issue, since it sounds like you were able to install the Toolkit.
