### ISSUE TITLE
Visual Studio won't load the extension

### ISSUE THREAD

**Issue by ifmason2** [aws/aws-toolkit-visual-studio#442]
Visual Studio won't load the extension.
I have a solution which contains some .NET projects and a Python project. The lambdas are built from the .NET projects, the python projects contain cmd line build utilities.
When I open the solution it throws an error something along the lines of 'an extension did the wrong thing'.
I have other solutions which don't contain python projects which are able to load fine

When I look at the extension logs I find:
`
2024-07-04 08:54:29,829 [7] ERROR AwsToolkit.VsSdk.Common.LambdaTester.LambdaTesterInstaller - Error configuring Lambda tester for DeployTools.pyproj
System.IO.FileNotFoundException: Could not find file 'C:\Projects\AWS\dd-lambda-functions\DeployTools.pyproj'.
File name: 'C:\Projects\AWS\dd-lambda-functions\DeployTools.pyproj'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at AwsToolkit.VsSdk.Common.LambdaTester.Project..ctor(String filename) in C:\codebuild\tmp\output\src2272085480\src\github.com\aws\aws-toolkit-visual-studio-staging\vspackages\shared\AwsToolkit.VsSdk.Common.Shared\LambdaTester\Project.cs:line 18
   at AwsToolkit.VsSdk.Common.LambdaTester.LambdaTesterInstaller.<InstallAsync>d__7.MoveNext() in C:\codebuild\tmp\output\src2272085480\src\github.com\aws\aws-toolkit-visual-studio-staging\vspackages\shared\AwsToolkit.VsSdk.Common.Shared\LambdaTester\LambdaTesterInstaller.cs:line 66
2024-07-04 08:54:29,833 [15] DEBUG Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterUtilities - Finished configuring Solution with Lambda Tester
2024-07-04 08:56:19,499 [1] ERROR Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterUtilities - Error configuring Lambda Tester on project. FileName: , FullName: , UniqueName: <MiscFiles>
System.Exception: Unable to determine project FileName
   at Amazon.AWSToolkit.VisualStudio.Lambda.LambdaTesterUtilities.<EnsureLambdaTesterConfiguredAsync>d__2.MoveNext()
2024-07-04 08:56:28,337 [9] ERROR AwsToolkit.VsSdk.Common.LambdaTester.LambdaTesterInstaller - Error configuring Lambda tester for DeployTools.pyproj
System.IO.FileNotFoundException: Could not find file 'C:\Projects\AWS\dd-lambda-functions\DeployTools.pyproj'.
File name: 'C:\Projects\AWS\dd-lambda-functions\DeployTools.pyproj'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at AwsToolkit.VsSdk.Common.LambdaTester.Project..ctor(String filename) in C:\codebuild\tmp\output\src2272085480\src\github.com\aws\aws-toolkit-visual-studio-staging\vspackages\shared\AwsToolkit.VsSdk.Common.Shared\LambdaTester\Project.cs:line 18
   at AwsToolkit.VsSdk.Common.LambdaTester.LambdaTesterInstaller.<InstallAsync>d__7.MoveNext() in C:\codebuild\tmp\output\src2272085480\src\github.com\aws\aws-toolkit-visual-studio-staging\vspackages\shared\AwsToolkit.VsSdk.Common.Shared\LambdaTester\LambdaTesterInstaller.cs:line 66
2024-07-04 08:56:50,360 [1] INFO  Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage - AWSToolkitPackage InitializeAsync started
2024-07-04 08:56:50,361 [1] DEBUG Amazon.AWSToolkit.Telemetry.TelemetryService - Telemetry service enabled
2024-07-04 08:56:50,361 [83] DEBUG Amazon.AWSToolkit.VisualStudio.Telemetry.TelemetryManager - Initializing Telemetry Service
2024-07-04 08:56:50,362 [84] INFO  Amazon.AWSToolkit.ResourceFetchers.FileResourceFetcher - Loading resource: C:\Users\iainm\AppData\Local/AWSToolkit\downloadedfiles\endpoints.json
2024-07-04 08:56:50,362 [83] DEBUG Amazon.AWSToolkit.Telemetry.Internal.TelemetryPublisher - TelemetryPublisher Timer started
2024-07-04 08:56:50,362 [83] DEBUG Amazon.AWSToolkit.VisualStudio.Telemetry.TelemetryManager - Telemetry Service Initialized
2024-07-04 08:56:50,362 [84] DEBUG Amazon.AWSToolkit.Telemetry.Internal.TelemetryPublisher - Starting Telemetry Publisher loop.
2024-07-04 08:56:50,367 [1] DEBUG Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage - Creating SAWSToolkitShellProvider service
2024-07-04 08:56:50,395 [89] INFO  Amazon.AWSToolkit.ResourceFetchers.FileResourceFetcher - Loading resource: C:\Users\iainm\AppData\Local/AWSToolkit\downloadedfiles\endpoints.json
2024-07-04 08:56:50,421 [1] DEBUG Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage - Setting up Publish to AWS functionality
2024-07-04 08:56:50,421 [1] ERROR Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage - Failed to properly set up Publish to AWS functionality
System.Exception: Already initialized
   at Amazon.AWSToolkit.Publish.Package.InitializePublishToAwsPackage.InitializePackageAsync(ToolkitContext toolkitContext, IAWSToolkitShellProvider shellProvider)
   at Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage.<InitializePublishToAwsAsync>d__91.MoveNext()
2024-07-04 08:56:50,422 [1] INFO  Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage - AWSToolkitPackage InitializeAsync complete
2024-07-04 08:56:50,423 [83] DEBUG Amazon.AWSToolkit.Telemetry.Internal.TelemetryPublisher - Telemetry Publisher loop has stopped.
2024-07-04 08:56:50,476 [89] INFO  Amazon.AWSToolkit.ResourceFetchers.HttpResourceFetcher - Loading resource: https://idetoolkits.amazonwebservices.com/endpoints.json
`
Which is correct. 
C:\Projects\AWS\dd-lambda-functions\DeployTools.pyproj does NOT exist.
However, C:\Projects\AWS\dd-lambda-functions\DeployTools\DeployTools.pyproj DOES and this is the file that is referred to in the solution:

Project("{888888A0-9F3D-457C-B088-3A5042F75D52}") = "DeployTools", "DeployTools\DeployTools.pyproj", "{42A43949-CCA2-4869-B2CA-022AEB16F094}"

[log_2024-07-04_08-58-35_14912.txt](https://github.com/user-attachments/files/16091526/log_2024-07-04_08-58-35_14912.txt)

This leaves me unable to open the extension or deploy my solution from visual studio.

**Development System (please complete the following information):**
- Windows Version:  Microsoft Windows 11 Pro
- Visual Studio Version: Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.10.3
- AWS Toolkit for Visual Studio Version: 1.54.0.1

**Comment by ifmason2** [comment]
Temporarily removing the python project from the solution does NOT fix the issue. The exception is no longer thrown, but the extension still won't load.

**Comment by awschristou** [comment]
Hi @ifmason2 , can you confirm that you are running 1.54.0.0 or 1.54.0.1? We just published version 1.54.0.1 a few minutes ago, but we aren't seeing our updated logging changes in your logs. It appears you are seeing the same issue reported in #441, so if you are able to install the latest version (1.54.0.1) and try again, we're interested in knowing if this addresses the issue for you.

**Comment by ifmason2** [comment]
Hi @awschristou. Initially I did check to see if there were updates and it told me I had the latest version. But checking again now the update has installed and things are working as expected, with the python project in the solution.
Thanks for the prompt response.

**Comment by ifmason2** [comment]
Working as expected

**Comment by awschristou** [comment]
Glad to hear it, thank you for letting us know it is working for you.
